cc_binary(
        name = "simple_example",
        srcs = ["simple_example.cpp"],
        deps = [
            "//lib:rateLimitter",
        ],
)

cc_binary(
        name = "simple_example_callback",
        srcs = ["simple_example_callback.cpp"],
        deps = [
            "//lib:rateLimitter",
        ],
)
