cc_binary(
        name = "simple_example",
        srcs = ["simple_example.cc"],
        deps = [
            "//lib:rateLimitter",
        ],
)

cc_binary(
        name = "simple_example_callback",
        srcs = ["simple_example_callback.cc"],
        deps = [
            "//lib:rateLimitter",
        ],
)
